--1.WAQTD EMPLOYEE NAME WHOSE SALARY IS GREATER THAN 3000 AFTER THE HIKE OF 10%.
SELECT ENAME, SAL, sal * (1.1) as SAL_AFTER_HIKE FROM EMPLOYEE WHERE (SAL * 1.1) > 3000;

--2. WAQTD EMPLOYEE NAME ALONG WITH ANNUAL SALARY WITH 10% HIKE IF THE EMPLOYEE WORKING UNDER 7566.
SELECT ENAME, (SAL*1.1)*12 AS ANNUAL_SAL FROM EMPLOYEE WHERE MGR = 7566;

--3. WAQTD EMPLOYEE DETAILS WHOSE NAME STARTS WITH 'K' AND ENDS WITH 'S'.
SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'K%S';

--4. WAQTD EMPLOLYEE DETAILS WHO HIRED BETWEEN 80-87 AND NAMES STARTS WITH CONSONANTS.
SELECT * FROM EMPLOYEE 
WHERE EXTRACT(YEAR FROM HIREDATE) BETWEEN 1980 AND 1987
  AND ENAME NOT LIKE 'A%' 
  AND ENAME NOT LIKE 'E%' 
  AND ENAME NOT LIKE 'I%' 
  AND ENAME NOT LIKE 'O%' 
  AND ENAME NOT LIKE 'U%';
--OTHER VERSION USING REGEXP
SELECT * 
FROM EMPLOYEE 
WHERE EXTRACT(YEAR FROM HIREDATE) BETWEEN 1980 AND 1987
AND REGEXP_LIKE(ENAME, '^[^AEIOU]');

--5. WAQTD NAMES STARTS WITH VOWELS AND ENDS WITH CONSONANTS.
SELECT * FROM EMPLOYEE 
WHERE REGEXP_LIKE(ENAME, '^[AEIOU].*[^AEIOU]$', 'i');

--6. WAQTD NAMES OF EMPLOYESS WHO WORKING AS A MANAGER.
SELECT ENAME FROM EMPLOYEE WHERE JOB = 'MANAGER';

--7. WAQTD EMPLOYEE NUMBER AND NAME WHO'S EARNING COMMISSION.
SELECT EMPNO, ENAME FROM EMPLOYEE WHERE COMM IS NOT NULL;

--8. DISPLAY THE NAMES OF THE EMPLOYEES WHO ARE WORKING IN DEPT 10 AND 20 .
SELECT ENAME FROM EMPLOYEE WHERE DEPTNO IN (20, 30);

--9.WAQTD NAMES OF ALL THE EMPLOYEES WHO ARE WORKING AS CLERKS AND EARNING A SALARY MORE THAN 3000.
SELECT ENAME FROM EMPLOYEE WHERE JOB = 'CLERK' AND SAL > 3000;

--10.DISPLAY THE ENAME OF THE EMPLOYEES WHO ARE WORKING AS CLERKS , SALESMAN OR ANALYST AND DRAWING A SALARY MORE THAN 2500.
SELECT ENAME FROM EMPLOYEE WHERE JOB IN ('CLERK', 'SALESMAN', 'ANALYST') AND SAL > 2500;

--11.DISPLAY THE LIST OF EMPLOYEES WHO HAVE JOINED A COMPANY BEFORE 1980 OR AFTER 1988.
SELECT ENAME, HIREDATE FROM EMPLOYEE WHERE EXTRACT(YEAR FROM HIREDATE)<1980 OR EXTRACT(YEAR FROM HIREDATE)>1988; 

--12.WAQTD THE NAMES OF THE EMPLOYEES WORKING IN DEPT 10,20,40 OR EMPLOYEE WORKING AS CLERK,SALESMAN,ANALYST.
SELECT ENAME FROM EMPLOYEE WHERE DEPTNO IN (10, 20, 40) OR JOB IN ('CLERK', 'SALESMAN', 'ANALYST');

--13.WAQTD THE NAME OF THE EMPLOYEES WHOSE NAME STARTS WITH 'S' AND HAVING FIVE CHARACTERS.
SELECT ENAME FROM EMPLOYEE WHERE ENAME LIKE 'S____';

--14.WAQTD THE NAME OF THE EMPLOYEES WHO ARE NOT GET COMM AND WORKING DEPTNO 10,20.
SELECT ENAME FROM EMPLOYEE WHERE COMM IS NULL AND DEPTNO IN (10, 20);

--15.WAQTD DETAILS OF THE EMPLOYEES ALONG WITH ANNUAL SALARY IF THEY ARE WORKING D EPT MANAGER AS 20,30 AND THEIR ANNUAL SALARY GREATER THAN 12000.
SELECT EMPNO, ENAME, JOB, (SAL*12) AS ANNUAL_SALARY FROM EMPLOYEE
WHERE DEPTNO IN (20, 30) AND (SAL*12) > 12000;


--16.WAQTD DETAILS OF EMPLOYEES WHO ARE HIRED FEB.
SELECT * FROM EMPLOYEE WHERE EXTRACT(MONTH FROM HIREDATE) = 2;

--17.WAQTD DETAILS OF EMPLOYEES ALONG WITH ANNUAL SALARY WHOSE NAME STARTS 'M' AND LAST BUT FIRST CHARACTER 'S'.
SELECT EMPLOYEE.*, (SAL * 12) AS ANUAL_SALARY FROM EMPLOYEE WHERE ENAME LIKE 'M%S_';

--18.WAQTD NAME AND HIREDATE OF EMPLOYEES WHO ARE HIRED BETWEEN JAN-81 AND DEC-81
SELECT ENAME, HIREDATE FROM EMPLOYEE WHERE HIREDATE BETWEEN DATE '1981-01-01' AND DATE '1981-12-31';

--19.WAQTD SALESMAN DETAILS.
SELECT * FROM EMPLOYEE WHERE JOB = 'SALESMAN';

--20.WAQTD DEPT DETAILS OF 10,20.
SELECT * FROM DEPARTMENT WHERE DEPTNO IN (10, 20);

--21.WAQTD THE DETAILS OF EMPLOYESS ALONG WITH HALF TERM SALARY WHO EARNIG SAL GREATER THAN 5000 AND NAME STARTS WITH VOWELS.
SELECT EMPLOYEE.*, (SAL*6) AS HALF_TERM_SAL FROM EMPLOYEE
WHERE SAL > 5000 AND (ENAME LIKE 'A%' OR ENAME LIKE 'E%' OR ENAME LIKE 'I%' OR ENAME LIKE 'O%' OR ENAME LIKE 'U%');

--22.WAQTD DETAILS OF EMPLOYESS WHO ARE NOT WORKING AS A MANAGER AND HAVING SAL IN BETWEEN 1000-2000.
SELECT * FROM EMPLOYEE WHERE JOB <> 'MANAGER' AND SAL BETWEEN 1000 AND 2000;

--23.WAQTD NAME OF EMPLOYEES WHO IS WORKING AS A CLERKS OR PRESIDENT.
SELECT ENAME FROM EMPLOYEE WHERE JOB IN ('CLERK', 'PRESIDENT');

--24.WAQTD LIST OF EMPLOYEES WHOSE SALARY RANGE BETWEEN 0-1400.
SELECT * FROM EMPLOYEE WHERE SAL BETWEEN 0 AND 1400;

--25.WAQTD NAMES OF EMPLOYEES WHO'S WORKING IN DEPT 10 AND HAVING SECOND LETTER AS 'M'.
SELECT ENAME FROM EMPLOYEE WHERE DEPTNO = 10 AND ENAME LIKE '_M%';

--26.WAQTD THE MAXIMUM SALARY OF DEPT 30 AND 20.
SELECT MAX(SAL) FROM EMPLOYEE WHERE DEPTNO IN (30, 20);

--27.WAQTD NAME OF THE EMPLOYEE WHO'S GETTING SALARY LESS THAN SMITH.
SELECT ENAME FROM EMPLOYEE WHERE SAL < (SELECT MAX(SAL) FROM EMPLOYEE WHERE ENAME = 'SMITH');

--28.WAQTD MINIMUM SALARIES GIVEN TO AN EMPLOYEE WORKING IN EACH DEPT.
SELECT DEPTNO, MIN(SAL) AS DEPT_MIN_SAL FROM EMPLOYEE GROUP BY DEPTNO;

--29.LIST ALL THE DEPT NAME THAT ARE HAVING ATLEAST 3 EMPLOYEES BUT NOT MORE THAN 5 EMPLOYEES IN IT.
SELECT D.DNAME FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
GROUP BY D.DNAME HAVING COUNT(EMPNO) BETWEEN 2 AND 5;

--30.WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPARTMENT EXCEPT SALESMAN.
SELECT DEPTNO, COUNT(EMPNO) AS DEPT_EMP_COUNT FROM EMPLOYEE GROUP BY DEPTNO;

--31.WAQTD DETAILS OF EMPLOYEES WHO ARE GETTING THE REPEATED SALARY.
SELECT * FROM EMPLOYEE
WHERE SAL IN (
    SELECT SAL
    FROM EMPLOYEE
    GROUP BY SAL
    HAVING COUNT(*) > 1
);

--32.WAQTD NUMBER OF EMPLOYESS WHO ARE HAVING SAME NAME .
SELECT COUNT(*) FROM EMPLOYEE
WHERE ENAME IN (
    SELECT ENAME
    FROM EMPLOYEE
    GROUP BY ENAME
    HAVING COUNT(*) > 1
);

--33.WAQTD AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPT EXCLUDING THE EMPLOYEES OF DEPT 10.
SELECT DEPTNO, AVG(SAL) AS AVG_SAL FROM EMPLOYEE WHERE DEPTNO <> 10 GROUP BY DEPTNO;

--34.WAQTD NAME AND TOTAL SALARY ODF THE EMPLOYEES IF THE EMPLOYEES ARE EARNING MORE THAN 2500.
--assuming total salary as the annaul salary below query is written
SELECT ENAME, (SAL*12) AS ANNUAL_SALARY FROM EMPLOYEE WHERE SAL > 2500;

--35. Find job roles with average salary betwe en 30,000 and 60,000.
SELECT JOB, AVG(SAL) AVG_SAL FROM EMPLOYEE
GROUP BY JOB HAVING AVG(SAL) BETWEEN 30000 AND 60000;

--36. List employees by department number in ascending order, and within each department by salary descending.
SELECT ENAME, DEPTNO, SAL FROM EMPLOYEE
ORDER BY DEPTNO ASC, SAL DESC;

--37. Show all employees ordered alphabetically by job title, then by name.
SELECT * FROM EMPLOYEE ORDER BY JOB, ENAME ASC;

--38. Retrieve employees earning more than 30,000 and sort them by salary in descending order.
SELECT * FROM EMPLOYEE WHERE SAL > 30000 ORDER BY SAL DESC;

--39. List employees from department 10, sorted by hire date (oldest first).
SELECT * FROM EMPLOYEE WHERE DEPTNO = 10 ORDER BY HIREDATE ASC;

--40. Display employee names and job titles ordered by job in descending order and salary ascending.
SELECT ENAME, JOB FROM EMPLOYEE ORDER BY JOB DESC, SAL ASC;