--1.WAQTD EMPLOYEE NAME WHOSE SALARY IS GREATER THAN 3000 AFTER THE HIKE OF 10%.
SELECT ENAME, SAL, sal * (1.1) as SAL_AFTER_HIKE FROM EMPLOYEE WHERE (SAL * 1.1) > 3000;

--2. WAQTD EMPLOYEE NAME ALONG WITH ANNUAL SALARY WITH 10% HIKE IF THE EMPLOYEE WORKING UNDER 7566.
SELECT ENAME, (SAL*1.1)*12 AS ANNUAL_SAL FROM EMPLOYEE WHERE MGR = 7566;

--3. WAQTD EMPLOYEE DETAILS WHOSE NAME STARTS WITH 'K' AND ENDS WITH 'S'.
SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'K%S';

--4. WAQTD EMPLOYEE DETAILS ALONG WITH MONTHLY SALARY WITH 10% DEDUCTION.
SELECT ENAME, SAL, SAL-(SAL * 10/100) FROM EMPLOYEE;

--5. WAQTD EMPLOLYEE DETAILS WHO HIRED BETWEEN 80-87 AND NAMES STARTS WITH CONSONANTS.
SELECT * FROM EMPLOYEE 
WHERE EXTRACT(YEAR FROM HIREDATE) BETWEEN 1980 AND 1987
AND REGEXP_LIKE(ENAME, '^[^AEIOU]');

--6. WAQTD NAMES STARTS WITH VOWELS AND ENDS WITH CONSONANTS.
SELECT * FROM EMPLOYEE 
WHERE REGEXP_LIKE(ENAME, '^[AEIOU].*[^AEIOU]$', 'i');

--7. WAQTD NAMES OF EMPLOYESS WHO WORKING AS A MANAGER.
SELECT ENAME FROM EMPLOYEE WHERE JOB = 'MANAGER';

--8. WAQTD EMPLOYEE NUMBER AND NAME WHO'S EARNING COMMISSION.
SELECT EMPNO, ENAME FROM EMPLOYEE WHERE COMM IS NOT NULL AND COMM <> 0;

--9. DISPLAY THE NAMES OF THE EMPLOYEES WHO ARE WORKING IN DEPT 10 AND 20 .
SELECT ENAME FROM EMPLOYEE WHERE DEPTNO IN (10,20);

--10. WAQTD NAMES OF ALL THE EMPLOYEES WHO ARE WORKING AS CLERKS AND EARNING A SALARY MORE THAN 3000.
SELECT ENAME FROM EMPLOYEE WHERE JOB = 'CLERK' AND SAL > 3000;

--11. DISPLAY THE ENAME OF THE EMPLOYEES WHO ARE WORKING AS CLERKS , SALESMAN OR ANALYST AND DRAWING A SALARY MORE THAN 2500.
SELECT ENAME FROM EMPLOYEE WHERE JOB IN ('CLERK', 'SALESMAN', 'ANALYST') AND SAL > 2500;

--12. DISPLAY THE LIST OF EMPLOYEES WHO HAVE JOINED A COMPANY BEFORE 1980 OR AFTER 1988.
SELECT ENAME, HIREDATE FROM EMPLOYEE WHERE EXTRACT(YEAR FROM HIREDATE)<1980 OR EXTRACT(YEAR FROM HIREDATE)>1988; 

--13. DISPLAY THE LIST OF EMPLOYEES WHO HIRED DURING BEFORE 1982 AND AFTER 1985.
SELECT ENAME, HIREDATE FROM EMPLOYEE WHERE EXTRACT(YEAR FROM HIREDATE)<1982 AND EXTRACT(YEAR FROM HIREDATE)>1985; 

--14. WAQTD THE NAMES OF THE EMPLOYEES WORKING IN DEPT 10,20,40 OR EMPLOYEE WORKING AS CLERK,SALESMAN,ANALYST.
SELECT ENAME FROM EMPLOYEE WHERE DEPTNO IN (10, 20, 40) OR JOB IN ('CLERK', 'SALESMAN', 'ANALYST');

--15. WAQTD THE NAME OF THE EMPLOYEES WHOSE NAME STARTS WITH 'S' AND HAVING FIVE CHARACTERS.
SELECT ENAME FROM EMPLOYEE WHERE ENAME LIKE 'S____';

--16. WAQTD THE NAME OF THE EMPLOYEES WHO ARE NOT GET COMM AND WORKING DEPTNO 10,20.
SELECT ENAME FROM EMPLOYEE WHERE (COMM IS NULL OR COMM = 0) AND DEPTNO IN (10, 20);

--17. WAQTD DETAILS OF THE EMPLOYEES ALONG WITH ANNUAL SALARY IF THEY ARE WORKING DEPT MANAGER AS 20,30 AND THEIR ANNUAL SALARY GREATER THAN 12000.
SELECT EMPNO, ENAME, JOB, (SAL*12) AS ANNUAL_SALARY FROM EMPLOYEE
WHERE DEPTNO IN (20, 30) AND (SAL*12) > 12000;

--18. --16.WAQTD DETAILS OF EMPLOYEES WHO ARE HIRED FEB.
SELECT * FROM EMPLOYEE WHERE EXTRACT(MONTH FROM HIREDATE) = 2;

--19. WAQTD DETAILS OF EMPLOYEES ALONG WITH ANNUAL SALARY WHOSE NAME STARTS 'M' AND LAST BUT FIRST CHARACTER 'S'.
SELECT EMPLOYEE.*, (SAL * 12) AS ANUAL_SALARY FROM EMPLOYEE WHERE ENAME LIKE 'M%S_';

--20. WAQTD NAME OF EMPLOYEES WHOSE NAME STARTS VOWELS AND NOT HAVE REPORTING MANAGER.
SELECT ENAME FROM EMPLOYEE WHERE REGEXP_LIKE(ENAME, '^[AEIOU]') AND MGR IS NULL;

--21. WAQTD NAME AND HIREDATE OF EMPLOYEES WHO ARE HIRED BETWEEN JAN-81 AND DEC-81
SELECT ENAME, HIREDATE FROM EMPLOYEE WHERE HIREDATE BETWEEN DATE '1981-01-01' AND DATE '1981-12-31';

--22. WAQTD SALESMAN DETAILS.
SELECT * FROM EMPLOYEE WHERE JOB = 'SALESMAN';

--23. WAQTD DEPT DETAILS OF 10,20, 30.
SELECT * FROM DEPARTMENT WHERE DEPTNO IN (10, 20, 30);

--24.WAQTD PLACE OF PRESIDENT.
SELECT E.ENAME, E.JOB, D.LOC FROM EMPLOYEE E
JOIN DEPARTMENT D USING(DEPTNO)
WHERE JOB = 'PRESIDENT';

--25. WAQTD THE DETAILS OF EMPLOYESS ALONG WITH HALF TERM SALARY WHO EARNIG SAL GREATER THAN 5000 AND NAME STARTS WITH VOWELS.
SELECT EMPLOYEE.*, (SAL*6) AS HALF_TERM_SAL FROM EMPLOYEE
WHERE SAL > 5000 AND REGEXP_LIKE(ENAME, '^[AEIOUaeiou]');

--26. WAQTD DETAILS OF EMPLOYESS WHO ARE NOT WORKING AS A MANAGER AND HAVING SAL IN BETWEEN 1000-2000.
SELECT * FROM EMPLOYEE WHERE JOB <> 'MANAGER' AND SAL BETWEEN 1000 AND 2000;

--27. WAQTD LIST OF EMPLOYEES WITH ANNUAL SALARY WHOSE ANNUAL SALARY IS 4LPA.
SELECT ENAME, SAL*12 AS ANNUAL_SALARY FROM EMPLOYEE WHERE (SAL*12) = 400000;

--28. WAQTD NAME OF EMPLOYEES WHO IS WORKING AS A CLERKS OR PRESIDENT.
SELECT ENAME FROM EMPLOYEE WHERE JOB IN ('CLERK', 'PRESIDENT');

--29. WAQTD LIST OF EMPLOYEES WHOSE SALARY RANGE BETWEEN 0-1400.
SELECT * FROM EMPLOYEE WHERE SAL BETWEEN 0 AND 1400;

--30. WAQTD NAMES OF EMPLOYEES WHO'S WORKING IN DEPT 10 AND HAVING SECOND LETTER AS 'M'.
SELECT ENAME FROM EMPLOYEE WHERE DEPTNO = 10 AND ENAME LIKE '_M%';

--31. WAQTD THE MAXIMUM SALARY OF DEPT 30 AND 20.
SELECT DEPTNO, MAX(SAL) FROM EMPLOYEE WHERE DEPTNO IN (20, 30) GROUP BY DEPTNO;

--32. WAQTD NAME OF THE EMPLOYEE WHO'S GETTING SALARY LESS THAN SMITH.
SELECT ENAME FROM EMPLOYEE WHERE SAL < ANY (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'SMITH');

--33. WAQTD NUMBER OF TIMES THE SALARIES PRESENT IN EMPLOYEE TABLE.
SELECT SAL, COUNT(SAL) FROM EMPLOYEE GROUP BY SAL;

--34. WAQTD MINIMUM SALARIES GIVEN TO AN EMPLOYEE WORKING IN EACH DEPT.
SELECT DEPTNO, MIN(SAL) AS DEPT_MIN_SAL FROM EMPLOYEE GROUP BY DEPTNO;

--35. LIST ALL THE DEPT NAME THAT ARE HAVING ATLEAST 3 EMPLOYEES BUT NOT MORE THAN 5 EMPLOYEES IN IT.
SELECT D.DNAME FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
GROUP BY D.DNAME HAVING COUNT(EMPNO) BETWEEN 3 AND 5;

--36. WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPARTMENT EXCEPT SALESMAN.
SELECT DEPTNO, COUNT(EMPNO) AS DEPT_EMP_COUNT FROM EMPLOYEE WHERE JOB <> 'SALESMAN' GROUP BY DEPTNO;

--37. WAQTD DETAILS OF EMPLOYEES WHO ARE GETTING THE REPEATED SALARY.
SELECT * FROM EMPLOYEE
WHERE SAL IN (
    SELECT SAL
    FROM EMPLOYEE
    GROUP BY SAL
    HAVING COUNT(*) > 1
);

--38. WAQTD NUMBER OF EMPLOYESS WHO ARE HAVING SAME NAME .
SELECT COUNT(*) FROM EMPLOYEE
WHERE ENAME IN (
    SELECT ENAME
    FROM EMPLOYEE
    GROUP BY ENAME
    HAVING COUNT(*) > 1
);

--39. WAQTD AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPT EXCLUDING THE EMPLOYEES OF DEPT 10.
SELECT DEPTNO, AVG(SAL) AS AVG_SAL FROM EMPLOYEE WHERE DEPTNO <> 10 GROUP BY DEPTNO;

--40. WAQTD NAME AND TOTAL SALARY ODF THE EMPLOYEES IF THE EMPLOYEES ARE EARNING MORE THAN 2500.
--assuming total salary as the annaul salary below query is written
SELECT ENAME, (SAL*12) AS ANNUAL_SALARY FROM EMPLOYEE WHERE SAL > 2500;

--41. DISPLAY LOCATION AND DNAME OF EMPLOYEE WHO ARE WORKING AS PRESIDENT WITH 1500 SALARY.
SELECT D.LOC, D.DNAME FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE E.JOB = 'PRESIDENT' AND E.SAL = 1500;

--42. WAQTD ALL THE EMPLOYEES WHOSE JOB NOT SAME AS SCOTT AND SALARY IS GREATER THAN ALLEN.
SELECT ENAME FROM EMPLOYEE 
WHERE JOB <> (SELECT JOB FROM EMPLOYEE WHERE ENAME = 'SCOTT') AND
SAL > (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'ALLEN');

--43. LIST DEPT NAME HAVING ATLEAST 3 SALESMAN.
SELECT D.DNAME
FROM DEPARTMENT D
JOIN EMPLOYEE E ON D.DEPTNO = E.DEPTNO
WHERE E.JOB = 'SALESMAN'
GROUP BY D.DNAME, D.DEPTNO
HAVING COUNT(E.EMPNO) >= 3;

--44. DISPLAY ALL THE EMPLOYEES WHO'S DEPT NAME ENDS WITH 'S'.
SELECT E.ENAME, D.DNAME FROM EMPLOYEE E 
JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME LIKE '%S'

--45. WAQTD JOB AND MAX SAL OF EMPLOYEE IN EACH JOB IF THE MAX SAL EXCEEDS 3000 ON EACH DEPT.
--40. WAQTD NAME AND TOTAL SALARY ODF THE EMPLOYEES IF THE EMPLOYEES ARE EARNING MORE THAN 2500.
--assuming total salary as the annaul salary below query is written
SELECT ENAME, (SAL*12) AS ANNUAL_SALARY FROM EMPLOYEE WHERE SAL > 2500;

--41. DISPLAY LOCATION AND DNAME OF EMPLOYEE WHO ARE WORKING AS PRESIDENT WITH 1500 SALARY.
SELECT D.LOC, E.ENAME FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE E.JOB = 'PRESIDENT' AND E.SAL = 1500;

--42. WAQTD ALL THE EMPLOYEES WHOSE JOB NOT SAME AS SCOTT AND SALARY IS GREATER THAN ALLEN.
SELECT ENAME FROM EMPLOYEE 
WHERE JOB <> (SELECT JOB FROM EMPLOYEE WHERE ENAME = 'SCOTT') AND
SAL > (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'ALLEN');

--43. LIST DEPT NAME HAVING ATLEAST 3 SALESMAN.
SELECT D.DNAME
FROM DEPARTMENT D
JOIN EMPLOYEE E ON D.DEPTNO = E.DEPTNO
WHERE E.JOB = 'SALESMAN'
GROUP BY D.DNAME, D.DEPTNO
HAVING COUNT(E.EMPNO) >= 3;

--44. DISPLAY ALL THE EMPLOYEES WHO'S DEPT NAME ENDS WITH 'S'.
SELECT E.ENAME, D.DNAME FROM EMPLOYEE E 
JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME LIKE '%S'

--45. WAQTD JOB AND MAX SAL OF EMPLOYEE IN EACH JOB IF THE MAX SAL EXCEEDS 3000 ON EACH DEPT.
SELECT JOB, MAX(SAL) FROM EMPLOYEE
GROUP BY JOB HAVING MAX(SAL) > 3000;

--46. WAQTD DEPT NAME WHO'S HAVING HIGHEST COMMISSION.
SELECT D.DNAME FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE E.COMM = (SELECT MAX(COMM) FROM EMPLOYEE);

--47. WAQTD THE EMPLOYEE NAME WHOSE DEPT NAME HAS 2ND CHARACTER AS 'O'.
SELECT E.ENAME FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME LIKE '_O%';

--48. WAQTD NAMES OF THE EMPLOYEES EARNING GREATER THAN MILLER.
SELECT ENAME FROM EMPLOYEE WHERE SAL > (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'MILLER');

--49. WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THE EMPLOYEE WAS HIRED AFTER JONES.
SELECT ENAME, HIREDATE FROM EMPLOYEE WHERE HIREDATE > (SELECT HIREDATE FROM EMPLOYEE WHERE ENAME = 'JONES'); 

--50. WAQTD ALL THE DEATILS OF EMPLOYEES WORKING AS SALESMAN IN THE DEPT 20 ABD EARNING COMM MORE THAN SMITH AND HIRED AFTER KING.
SELECT * FROM EMPLOYEE WHERE JOB = 'SALESMAN' AND DEPTNO = 20 AND
 COMM > (SELECT NVL(COMM,0) FROM EMPLOYEE WHERE ENAME = 'SMITH') AND
HIREDATE > (SELECT HIREDATE FROM EMPLOYEE WHERE ENAME = 'KING');

--51. WAQTD NAMES OF THE EMPLOYEES EARNING MORE THAN SMITH IN SALES DEPT.
SELECT ENAME FROM EMPLOYEE WHERE SAL > ANY
(SELECT SAL FROM EMPLOYEE WHERE ENAME = 'SMITH') AND
DEPTNO = (SELECT DEPTNO FROM DEPARTMENT WHERE DNAME = 'SALES');

--52. WAQTD DETAILS OF THE EMPLOYEES WORKING AS ANALYST IN THE LOCATION DALLAS.
SELECT * FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE E.JOB = 'ANALYST' AND D.LOC = 'DALLAS';

--53. DISPLAY ALL THE EMPLOYEES WHOSE LOCATION NAME ENDING WITH 'S'.
SELECT E.* FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.LOC LIKE '%S';

--54. WAQTD NAME , ANNUAL SALARY OF THE EMPLOYEES IF THEIR ANNUAL SALARY IS MORE THAN ALL THE MANAGER.
SELECT ENAME, (SAL*12) AS ANNUAL_SALARY FROM EMPLOYEE WHERE SAL > ALL 
(SELECT SAL FROM EMPLOYEE WHERE JOB = 'MANAGER');

--55. WAQTD DETAILS OF EMPLOYESS WHOSE HIREDATE GREATER THAN SALESMAN.
SELECT * FROM EMPLOYEE WHERE HIREDATE > ALL (SELECT HIREDATE FROM EMPLOYEE WHERE JOB = 'SALESMAN');

--56. WAQTD THE PRESIDENT SALARY.
SELECT SAL FROM EMPLOYEE WHERE JOB = 'PRESIDENT';

--57. WAQTD THE COUNT OF EMP IN EACH DEPT.
SELECT DEPTNO, COUNT(EMPNO) AS COUNT_OF_EMP_PER_DEPT FROM EMPLOYEE GROUP BY DEPTNO;

--58. WAQTD THE DNAME OF EMP OF EACH DEPT.
SELECT E.ENAME, D.DNAME FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO;

--59. WAQTD SALARY GREATER THAN ALLEN AND SMITH.
SELECT SAL FROM EMPLOYEE WHERE SAL > ALL
(SELECT SAL FROM EMPLOYEE WHERE ENAME IN ('ALLEN', 'SMITH'));

--60. WAQTD DETAILS OF AN EMPLOYEE WHOSE SALARY IS GREATER THAN ALLEN AFTER THE HIKE OF 10%.
SELECT * FROM EMPLOYEE WHERE (SAL*1.1) > (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'ALLEN');

--61. WAQTD DEPARTMENT NAME OF THE EMPLOYEES WHO ARE HIRED AFTER THE ALLEN INTO SALES DEPARTMENT.
SELECT E.ENAME, D.DNAME FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME = 'SALES' AND E.HIREDATE > (SELECT HIREDATE FROM EMPLOYEE WHERE ENAME = 'ALLEN');

--62. WAQTD JOINED DATE AND REPOTRTING MANAGER NUMBER IF AN EMPLOYEE WORKING IN BOSTON.
SELECT E.HIREDATE, E.MGR FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.LOC = 'BOSTON';

--63. WAQTD NAMES AND JOB OF AN EMPLOYEES IN EACH JOB IF THERE ARE TWO EMPLOYEES NAME SHOULD STARTS WITH 'S' OR 'P'.
SELECT job, LISTAGG(ename, ', ') WITHIN GROUP (ORDER BY ename) AS employee_names
FROM employee
WHERE ename LIKE 'S%' OR ename LIKE 'P%'
GROUP BY job
HAVING COUNT(*) = 2;

--64. WAQTD NO OF EMPLOYEES ARE WORKING IN EACH DEPARMENT IN THE CHICAGO.
SELECT DNAME, COUNT(*) AS EMP_CNT FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.LOC = 'CHICAGO' GROUP BY D.DNAME;

--65. WAQTD EMP NAME, JOB, LOCATION OF ALL EMPLOYEES WHO ARE WORKING AS A MANAGER AND WORKS AT CHICAGO.
SELECT E.ENAME, E.JOB, D.LOC FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE E.JOB = 'MANAGER' AND D.LOC = 'CHICAGO';

--66. LIST EMPLOYEES FROM SALES AND RESEARCH DEPARTMENT HAVING ATLEAST 2 REPORTING EMPLOYEES.
WITH MANAGERS AS (SELECT * FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME IN ('RESEARCH', 'SALES') AND JOB = 'MANAGER')
SELECT MGR,COUNT(*) FROM EMPLOYEE WHERE MGR IN (SELECT EMPNO FROM MANAGERS) GROUP BY MGR HAVING COUNT(*) >= 2;

--67. DISPLAY THE LOCATION OF ALL THE DEPARTMENTS WHICH HAVE EMPLOYEES JOINED IN THE YEAR 81.
SELECT DISTINCT D.DNAME, D.LOC FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE EXTRACT(YEAR FROM HIREDATE) = 1981;

--68. WAQTD NAME OF THE EMPLOYEES EARNING SALARY MORE THAN THE ANALYST.
SELECT ENAME FROM EMPLOYEE WHERE SAL > ALL (SELECT SAL FROM EMPLOYEE WHERE JOB = 'ANALYST');

--69.WAQTD NAME OF THE EMPLOYEES IF THE EMPLOYEE EARNS SALARY LESS THAN ATLEAST A MANAGER.
SELECT ENAME FROM EMPLOYEE WHERE SAL < ANY (SELECT SAL FROM EMPLOYEE WHERE JOB = 'MANAGER');

--70. WAQTD EMP NAMES IF EMPLOYEES ARE HIRED AFTER ALL THE EMPLOYEES OF DEPT 30.
SELECT ENAME FROM EMPLOYEE WHERE HIREDATE > ALL (SELECT HIREDATE FROM EMPLOYEE WHERE DEPTNO = 30);

--71. WAQTD DETAILS IF THE EMPLOYEES WORKING IN NEWYORK OR DALLAS.
SELECT * FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.LOC IN ('NEW YORK', 'DALLAS');

--72. WAQTD LOC OF THE EMPLOYEES IF THEY EARN COMISSION IN DEPT 20.
SELECT D.LOC FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE E.COMM IS NOT NULL AND E.COMM <> 0 AND E.DEPTNO = 20;

--73. WAQTD ALL THE DETAILS OF EMPLOYEES WORKING IN THE SAME DESIGNATION AS JONES AND WORKS IN LOCATION CHICAGO.
SELECT * FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE JOB = (SELECT JOB FROM EMPLOYEE WHERE ENAME = 'JONES') AND D.LOC = 'CHICAGO';

--74. WAQTD NAMES OF THE EMPLOYEES WHO EARNING MORE THAN SCOTT.
SELECT ENAME FROM EMPLOYEE WHERE SAL > (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'SCOTT');

--75. WAQTD NUMBER OF EMPLOYEES AND AVG SALARY NEEDED TO PAY THE EMPLOYEES WHOSE SALARY GREATER THAN 3000 IN EACH DEPT.
SELECT DEPTNO, COUNT(*) AS NO_OF_EMPLOYEES, ROUND(AVG(SAL),2) AS AVERAGE_SALARY FROM EMPLOYEE WHERE SAL > 3000 GROUP BY DEPTNO;


/*76. WAQTD ENAME AND SAL OF ALL THE EMPLOYEE WHO ARE EARNING MORE THAN CLARK BUT LESS THAN CLARK.
--This question is not clear, so I'm rewriting the question as
WAQTD ENAME AND SAL OF ALL THE EMPLOYEE WHO ARE EARNING MORE THAN CLARK BUT LESS THAN MOSSY.*/
SELECT ENAME, SAL FROM EMPLOYEE WHERE SAL BETWEEN (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'CLARK') AND 
(SELECT SAL FROM EMPLOYEE WHERE ENAME = 'MOSSY');


--77. WAQTD DETAILS OF ALL THE EMPLOYEES WORKING IN DEPT 30 AND WORKING IN THE SAME DESIGNATION AS JAMES.
SELECT * FROM EMPLOYEE WHERE DEPTNO = 30 AND JOB = 
(SELECT JOB FROM EMPLOYEE WHERE ENAME = 'JAMES');

--78. WAQTD NAME OF THE EMPLOYEES WHO'S NAME STARTS WITH 'B' AND WORK IN THE SAME DESIGNATION AS CLARK.
SELECT ENAME FROM EMPLOYEE WHERE ENAME LIKE 'B%' AND JOB = 
(SELECT JOB FROM EMPLOYEE WHERE ENAME = 'CLARK');

--79. WAQTD LOC AND DNAME OF THE EMPLOYEES WHOS SALARY IS 1250 RUPEES.
SELECT D.LOC, D.DNAME FROM DEPARTMENT D JOIN EMPLOYEE E ON D.DEPTNO = E.DEPTNO 
WHERE E.SAL = 1250;

--80. WAQTD DNAME AND LOC OF THE EMPLOYEES WHO'S NAME HAS CHARACTER 'M' IN IT.
SELECT D.DNAME, D.LOC FROM DEPARTMENT D JOIN EMPLOYEE E ON D.DEPTNO = E.DEPTNO 
WHERE E.ENAME LIKE '%M%';

--81. WAQTD DEPTNO OF THERE ARE ATLEAST 4 EMP IN EACH DEPT WHOSE NAME HAS CHARACTER 'A' IN IT.
--Write a query to display the department numbers (DEPTNO) that have at least four employees whose names contain the letter 'A'.
SELECT DEPTNO, COUNT(*) FROM EMPLOYEE WHERE ENAME LIKE '%A%' GROUP BY DEPTNO HAVING COUNT(*) >= 4;

--82. WAQTD ENAME AND SAL OF THE EMPLOYEES IF THEY ARE WORKING AS SALESMAN.
SELECT ENAME, SAL FROM EMPLOYEE WHERE JOB = 'SALESMAN';

--83. WAQTD ENAME OF THE EMPLOYEES IF THEY ARE EARNING SALARY GREATER THAN 2000 AND HIRED BETWEEN 80-86 AND THEIR NAME ENDS WITH VOWELS.
SELECT ENAME FROM EMPLOYEE WHERE SAL > 2000 AND 
(EXTRACT(YEAR FROM HIREDATE) BETWEEN 1980 AND 1986) AND
REGEXP_LIKE(ENAME,'[AEIOUaeiou]$');

--84.WAQTD NAMES AND HIREDATE OF THE EMPLOYEES IF THEY HIRED DURING THE YEAR 82-85 AND EARNING THE SALARY IN BETWEEN 1000-2800.
SELECT ENAME, HIREDATE FROM EMPLOYEE WHERE (EXTRACT(YEAR FROM HIREDATE) BETWEEN 1982 AND 1985)
AND (SAL BETWEEN 1000 AND 2800);

--85. WAQTD THE PLACE WHICH ARE DUPLICATED IN DEPT TABLE.
SELECT LOC, COUNT(*) FROM DEPARTMENT GROUP BY LOC HAVING COUNT(*) > 1;

--86. WAQTD NUMBER OF EMPS WHO HAS HIRED ON THE SAME DAY IN EACH DEPT.
SELECT DEPTNO, HIREDATE, COUNT(*) FROM EMPLOYEE GROUP BY DEPTNO, HIREDATE HAVING COUNT(*) > 1;

--87. WAQTD NAMES OF THE EMPLOYEES EARNING LESS THAN KING , FORD.
SELECT ENAME FROM EMPLOYEE WHERE SAL < ALL (SELECT SAL FROM EMPLOYEE WHERE ENAME IN ('KING', 'FORD'));

--88. WAQTD DETAILS OF EMPLOYEES WORKING NEWYORK OR CHICAGO.
SELECT E.* FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.LOC IN ('NEW YORK', 'CHICAGO');

--89. WAQTD NAME AND HIREDATE OF ALL THE EMPLOYEES WHO ARE HIRED BEFORE ANALYST.
SELECT ENAME, HIREDATE FROM EMPLOYEE WHERE HIREDATE < ALL
(SELECT HIREDATE FROM EMPLOYEE WHERE JOB = 'ANALYST');

--90. WAQTD NAMES OF EMPLOYEES EARNING MORE THAN ADAMS IN RESEARCH DEPT.
SELECT ENAME FROM EMPLOYEE WHERE SAL >
(SELECT E.SAL FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO WHERE E.ENAME = 'ADAMS' AND D.DNAME = 'RESEARCH');

/*91. DISPLAY ALL THE EMPLOYEES WHO ARE MANAGER'S HAVING 'K' AS THE LAST BUT ONE CHARACTER IN NAME AND
 EARNING THE SALARY IN BETWEEN 2500-2851.*/
--81. WAQTD DEPTNO OF THERE ARE ATLEAST 4 EMP IN EACH DEPT WHOSE NAME HAS CHARACTER 'A' IN IT.
--Write a query to display the department numbers (DEPTNO) that have at least four employees whose names contain the letter 'A'.
SELECT DEPTNO, COUNT(*) FROM EMPLOYEE WHERE ENAME LIKE '%A%' GROUP BY DEPTNO HAVING COUNT(*) >= 4;

--82. WAQTD ENAME AND SAL OF THE EMPLOYEES IF THEY ARE WORKING AS SALESMAN.
SELECT ENAME, SAL FROM EMPLOYEE WHERE JOB = 'SALESMAN';

--83. WAQTD ENAME OF THE EMPLOYEES IF THEY ARE EARNING SALARY GREATER THAN 2000 AND HIRED BETWEEN 80-86 AND THEIR NAME ENDS WITH VOWELS.
SELECT ENAME FROM EMPLOYEE WHERE SAL > 2000 AND 
(EXTRACT(YEAR FROM HIREDATE) BETWEEN 1980 AND 1986) AND
REGEXP_LIKE(ENAME,'[AEIOUaeiou]$');

--84.WAQTD NAMES AND HIREDATE OF THE EMPLOYEES IF THEY HIRED DURING THE YEAR 82-85 AND EARNING THE SALARY IN BETWEEN 1000-2800.
SELECT ENAME, HIREDATE FROM EMPLOYEE WHERE (EXTRACT(YEAR FROM HIREDATE) BETWEEN 1982 AND 1985)
AND (SAL BETWEEN 1000 AND 2800);

--85. WAQTD THE PLACE WHICH ARE DUPLICATED IN DEPT TABLE.
SELECT LOC, COUNT(*) FROM DEPARTMENT GROUP BY LOC HAVING COUNT(*) > 1;

--86. WAQTD NUMBER OF EMPS WHO HAS HIRED ON THE SAME DAY IN EACH DEPT.
SELECT DEPTNO, HIREDATE, COUNT(*) FROM EMPLOYEE GROUP BY DEPTNO, HIREDATE HAVING COUNT(*) > 1;

--87. WAQTD NAMES OF THE EMPLOYEES EARNING LESS THAN KING , FORD.
SELECT ENAME FROM EMPLOYEE WHERE SAL < ALL (SELECT SAL FROM EMPLOYEE WHERE ENAME IN ('KING', 'FORD'));

--88. WAQTD DETAILS OF EMPLOYEES WORKING NEWYORK OR CHICAGO.
SELECT E.* FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.LOC IN ('NEWYORK', 'CHICAGO');

--89. WAQTD NAME AND HIREDATE OF ALL THE EMPLOYEES WHO ARE HIRED BEFORE ANALYST.
SELECT ENAME, HIREDATE FROM EMPLOYEE WHERE HIREDATE < ALL
(SELECT HIREDATE FROM EMPLOYEE WHERE JOB = 'ANALYST');

--90. WAQTD NAMES OF EMPLOYEES EARNING MORE THAN ADAMS IN RESEARCH DEPT.
SELECT ENAME FROM EMPLOYEE WHERE SAL >
(SELECT E.SAL FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO WHERE E.ENAME = 'ADAMS' AND D.DNAME = 'RESEARCH');

/*91. DISPLAY ALL THE EMPLOYEES WHO ARE MANAGER'S HAVING 'K' AS THE LAST BUT ONE CHARACTER IN NAME AND
 EARNING THE SALARY IN BETWEEN 2500-2851.*/
SELECT E.ENAME FROM EMPLOYEE E JOIN EMPLOYEE M ON E.MGR = M.EMPNO
WHERE M.ENAME LIKE '%K_' AND (E.SAL BETWEEN 2500 AND 2851);


--92. WAQTD DETAILS OF THE EMPLOYEES ALONG WITH ANNUAL SALARY IF EMPLOYEES ARE WORKING IN DALLAS.
SELECT E.ENAME, (E.SAL * 12) AS ANNUAL_SALARY FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE D.LOC = 'DALLAS';

--93.WAQTD NAMES OF EMPLOYEES IF THEY ARE EARNING MORE THAN TURNER IN DEPT 30 AND WORKING IN CHICAGO.
SELECT ENAME FROM EMPLOYEE WHERE SAL >
(SELECT E.SAL FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE ENAME = 'TURNER' AND E.DEPTNO = 30 AND D.LOC = 'CHICAGO');

--94. WAQTD NAMES OF ALL THE EMPLOYEES WHO ARE EARNING LESS THAN ANYONE OF THE ANALAYST.
SELECT ENAME FROM EMPLOYEE WHERE SAL < ANY (SELECT SAL FROM EMPLOYEE WHERE JOB = 'ANALYST');

--95. DISPLAY DEPARTMENT NAME OF ALL THE EMPLOYEES WHO ARE REPORTING TO BLAKE.
SELECT D.DNAME FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO 
WHERE E.MGR = (SELECT EMPNO FROM EMPLOYEE WHERE ENAME = 'BLAKE');

--96. WAQTD HIREDATE OF EMPLOYEE WHO HIRED BEFORE MARTIN INTO SALES DEPT.
SELECT HIREDATE FROM EMPLOYEE WHERE HIREDATE <
(SELECT HIREDATE FROM EMPLOYEE WHERE ENAME = 'MARTIN') AND DEPTNO = (SELECT DEPTNO FROM DEPARTMENT WHERE DNAME = 'SALES');

--97. WAQTD THE DEPTNO OF EMP WHO ARE WORKING IN SALES DEPT AND THEY ARE WORKING AS MANAGER.
SELECT E.DEPTNO FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO 
WHERE D.DNAME = 'SALES' AND E.JOB = 'MANAGER';

--98.WAQTD THE LOCATION OF THE EMPLOYEES, WHOSE DOES NOT START WITH 'S' AND HIRED DURING 80-82.
SELECT D.LOC FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE E.ENAME NOT LIKE 'S%' AND EXTRACT(YEAR FROM HIREDATE) BETWEEN 1980 AND 1982;

--99.WAQTD AVG SALARY , MAX SALARY , TOTAL SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH JOB EXCEPT SALESMAN.
SELECT JOB, ROUND(AVG(SAL),2) AS AVERAGE_SALARY, MAX(SAL) MAXIMUM_SALARY, SUM(SAL) AS TOTAL_SALARY FROM EMPLOYEE
WHERE JOB <> 'SALESMAN' GROUP BY JOB;

/*100. WAQTD THE NAMES OF THE EMP WHO HAS 2 A'S IN THEIR NAME AND WORKING IN DEPT
20 AND EARNIG SALARY IN THE RANGE OF 1099-1500 AND HIRED BETWEEN 85-88 INTO THE
RESEARCH DEPT .*/--DEPARTMENT 20 IS RESEARCH DEPARTMENT SO i'M NOT ADDING ONE MORE FILTER FOR RESEARCH DEPARTMENT
SELECT ENAME FROM EMPLOYEE WHERE ENAME LIKE '%A%A%' AND DEPTNO = 20 AND (SAL BETWEEN 1099 AND 1500)
AND (EXTRACT(YEAR FROM HIREDATE) BETWEEN 1985 AND 1988);

--PART 2
--1) Write a Query to display all the details of employee if the salary ranges between 500 and 250 and department number either 10, 20, 30.
SELECT * FROM EMPLOYEE WHERE (SAL BETWEEN 500 AND 250) AND
DEPTNO IN (10,20,30);

/*2) Write a Query to display all the employee who belongs to department number 10 or 20 and
comm between 1000 and 3000 and were hired during 1980 to 1983.*/
SELECT * FROM EMPLOYEE WHERE DEPTNO IN (10,20) AND (COMM BETWEEN 1000 AND 3000)
AND (EXTRACT(YEAR FROM HIREDATE) BETWEEN 1980 AND 1983);

--3) Write a Query to display all the details of employee if he is not having the reporting manager.
SELECT * FROM EMPLOYEE WHERE MGR IS NULL;

--4) List the employee where salary is between 2000 and 3000.
SELECT * FROM EMPLOYEE WHERE SAL BETWEEN 2000 AND 3000;

--5) List all the salesman in department number 30 and having salary greater than 5000.
SELECT * FROM EMPLOYEE WHERE DEPTNO = 30 AND JOB = 'SALESMAN' AND SAL > 5000;

--6) List all the employees who are having reporting manager in department 10.
SELECT E.ENAME FROM EMPLOYEE E JOIN EMPLOYEE M ON E.MGR = M.EMPNO 
WHERE M.DEPTNO = 10;

--7) Write a Query to display all the details of the employee if their job is having one _(underscore) in it.
SELECT * FROM EMPLOYEE WHERE JOB LIKE '%\_%' ESCAPE '\';

--8) Write a Query to display who are having % in their names.
SELECT ENAME FROM EMPLOYEE WHERE ENAME LIKE '%@%%' ESCAPE '@';

--9) Write a Query to display who are having _(underscore) as second character in their name.
SELECT * FROM EMPLOYEE WHERE JOB LIKE '_\_%' ESCAPE '\';

--10) Write a Query to display all the employee who are getting some comm with their designation is neither manager nor analyst.
SELECT * FROM EMPLOYEE WHERE COMM IS NOT NULL AND COMM <> 0 AND JOB NOT IN ('MANAGER', 'ANALYST');

--11) Write a Query to display all the manager whose annual salary is ending with 0.
SELECT * FROM EMPLOYEE WHERE JOB = 'MANAGER' AND MOD(SAL*12, 10) = 0;

--12) Write a Query to display all the employee who are clerk and analyst with salary greater than 1000.
SELECT * FROM EMPLOYEE WHERE JOB IN ('CLERK', 'ANALYST') AND SAL > 1000;

--13) Write a Query to display all the employee who are joined after year 81.
SELECT * FROM EMPLOYEE WHERE EXTRACT(YEAR FROM HIREDATE) > 1981;

--14) Write a Query to display all the employees who are joined in Feb.
SELECT * FROM EMPLOYEE WHERE EXTRACT(MONTH FROM HIREDATE) = 2;

--15) List the employee who are not working as manager and clerk in depart no 10 and 20 with salary in the range of 1000 to 3000.
SELECT * FROM EMPLOYEE WHERE JOB NOT IN ('MANAGER','CLERK') AND DEPTNO IN (10,20) 
AND SAL BETWEEN 1000 AND 3000;

--16) List the employees whose salary not in the range of 1000 to 2000 in depart no 10, 20, 30 except all salesman.
SELECT * FROM EMPLOYEE WHERE (SAL NOT BETWEEN 1000 AND 2000) AND DEPTNO IN (10,20,30) 
AND JOB <> 'SALESMAN';

/*17) Write a Query to display maximum salary, minimum salary and average salary of the 
organization by excluding employees who is working as salesman.*/
SELECT MAX(SAL) AS MAXIMUM_SALARY, MIN(SAL) AS MINIMUM_SALARY, AVG(SAL) AS AVERAGE_SALARY
FROM EMPLOYEE WHERE JOB <> 'SALESMAN';

--18) Write a Query to display number of employees by their total salary who are working in department number 20,30.
SELECT 
    (SAL * 12) + COALESCE(COMM, 0) AS annual_total_salary, 
    COUNT(*) AS employee_count
FROM EMPLOYEE 
WHERE DEPTNO IN (20, 30)
GROUP BY (SAL * 12) + COALESCE(COMM, 0);

--19)Write a Query to display max salary,min salary only if the name is start with A or S or M.
SELECT MAX(SAL) AS MAXIMUM_SALARY, MIN(SAL) AS MINIMUM_SALARY FROM EMPLOYEE
WHERE REGEXP_LIKE(ENAME, '^[ASM]');

--20) Write a Query to display number of employee in department number 30 working as salesman.
SELECT COUNT(*) AS NO_OF_EMPLOYEE FROM EMPLOYEE WHERE DEPTNO = 30 AND JOB = 'SALESMAN';

--21) Write a Query to display average salary given to the manager of the organization.
SELECT AVG(SAL) AVG_MANAGER_SALARY FROM EMPLOYEE WHERE JOB = 'MANAGER';

--22) Write a query to display number of employee department number 10 and number of employee in department number 30.
SELECT DEPTNO, COUNT(*) FROM EMPLOYEE WHERE DEPTNO IN (10,30) GROUP BY DEPTNO;

--23) Write a Query to display total salary and average salary for every department.
SELECT DEPTNO, SUM(SAL) AS DEPT_TOTAL_SALARY, ROUND(AVG(SAL),2) DEPT_AVG_SAL FROM EMPLOYEE
GROUP BY DEPTNO;

--24) Write a Query to display max sal and min sal in each designation.
SELECT JOB, MAX(SAL) JOB_MAX_SAL, MIN(SAL) JOB_MIN_SAL FROM EMPLOYEE GROUP BY JOB;

--25) Write a Query to display total salary of every department by excluding employee whose salary is greater than 3000.
SELECT DEPTNO, SUM(SAL) TOTAL_SALARY FROM EMPLOYEE WHERE SAL < 3000 GROUP BY DEPTNO;

--26) Write a Query to display job wise max salary in each department. 
SELECT DEPTNO, JOB, MAX(SAL) AS max_salary FROM EMPLOYEE
GROUP BY DEPTNO, JOB;

--27) Write a Query to display department number of more than 4 employees.
SELECT DEPTNO FROM EMPLOYEE GROUP BY DEPTNO HAVING COUNT(*) > 4;

--28) Write a Query to display job wise highest salary only if the highest salary is more than 1500.
SELECT JOB, MAX(SAL) JOB_MAX_SALARY FROM EMPLOYEE GROUP BY JOB HAVING MAX(SAL) > 1500;

--29) Write a Query to display job wise highest salary only if the highest salary is more than 1500 excluding department number 30
SELECT JOB, MAX(SAL) JOB_MAX_SALARY FROM EMPLOYEE WHERE DEPTNO <> 30
GROUP BY JOB HAVING MAX(SAL) > 1500;

--30) Write a Query to display department number along with number of employees in it.
SELECT DEPTNO, COUNT(*) AS NO_OF_EMPLOYEES FROM EMPLOYEE GROUP BY DEPTNO;

--31) Write a Query to display the department number which are having more than 4 employee in them.
SELECT DEPTNO FROM EMPLOYEE GROUP BY DEPTNO HAVING COUNT(*) > 4;

--32) Write a Query to display the max salary for each of the job excluding all the employee whose name end with S.
SELECT JOB, MAX(SAL) AS MAXIMUM_SALARY FROM EMPLOYEE WHERE ENAME NOT LIKE '%S'
GROUP BY JOB;

--33) Write a Query to display the department number which are having more than 9000 as their departmental total salary.
SELECT DEPTNO FROM EMPLOYEE GROUP BY DEPTNO
HAVING SUM(SAL) > 9000;

/*34) Write a Query to display department wise highest salary only if the highest salary in
between 5000 and 10000 and total salary of department is below 10000.*/
SELECT DEPTNO, MAX(SAL) AS HIGHEST_SALARY FROM EMPLOYEE GROUP BY DEPTNO
HAVING (MAX(SAL) BETWEEN 5000 AND 10000) AND SUM(SAL) < 10000;

/*35)Write a Query to display job wise total salary in each department only if department number
10, 20 total salary is less than 10000.*/
SELECT JOB, SUM(SAL) AS TOTAL_SALARY FROM EMPLOYEE WHERE DEPTNO IN (10, 20)
GROUP BY JOB HAVING SUM(SAL) < 10000;

--36) Write a Query to display average salary of each department by excluding all employees who do not have reporting manager.
SELECT DEPTNO, ROUND(AVG(SAL),2) AS DEPT_AVG_SALARY FROM EMPLOYEE WHERE MGR IS NOT NULL
GROUP BY DEPTNO;

/*37) Write a Query to display max, min, sum, average, commission and salaries for all the
department which is having employee hired within 1980 and 1985.*/
SELECT MAX(SAL) AS MAXIMUM_SALARY, MIN(SAL) AS MINIMUM_SALARY, SUM(SAL) AS TOTAL_SALARY, AVG(SAL) AS AVERAGE_SALARY,
MAX(COMM) AS MAXIMUM_COMM, MIN(COMM) AS MINIMUM_COMM, SUM(SAL) AS TOTAL_COMM, AVG(SAL) AS AVERAGE_COMM
FROM EMPLOYEE WHERE EXTRACT(YEAR FROM HIREDATE) BETWEEN 1980 AND 1985;

--38) Write a Query to display all the details of employee whose designation is same as martin.
SELECT * FROM EMPLOYEE WHERE JOB = (SELECT JOB FROM EMPLOYEE WHERE ENAME = 'MARTIN');

--39) Write a Query to display all the employee who were hired after recruiting miller.
SELECT ENAME FROM EMPLOYEE WHERE HIREDATE >
(sELECT HIREDATE FROM EMPLOYEE WHERE ENAME = 'MILLER');

--40) Write a Query to display name of an employee along with the annual salary if the employee is working in newyork.
SELECT E.ENAME, (E.SAL*12) AS ANNUAL_SALARY FROM EMPLOYEE E JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO WHERE D.LOC = 'NEW YORK';

--41) Write a Query to display all the details of employee who are working in same department of smith or allen.
SELECT * FROM EMPLOYEE WHERE DEPTNO IN (SELECT DEPTNO FROM EMPLOYEE WHERE ENAME IN ('SMITH', 'ALLEN'));

--44) Write a Query to display duplicate names in an employee table.
SELECT ENAME FROM EMPLOYEE GROUP BY ENAME HAVING COUNT(*) > 1;

/*45) Write a Query to display all the names of the employee only, if their name starts with vowel
and their location ends with vowel.*/
SELECT E.ENAME FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE REGEXP_LIKE(E.ENAME, '^[AEIOUaeiou]') and REGEXP_LIKE(D.LOC, '[AEIOUaeiou]$');

--46) Display Ename, job of all the managers and clerks who works in accounts and sales department
SELECT E.ENAME, E.JOB FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO
WHERE E.JOB IN ('MANAGER','CLERK') AND D.DNAME IN ('SALES','ACCOUNTING');

--47)Write a Query to display the second maximum salary.
SELECT MAX(SAL) AS "2ND_MAX_SALARY" FROM EMPLOYEE WHERE SAL < (SELECT MAX(SAL) FROM EMPLOYEE);

--48) Write a Query to display the third maximum salary.
WITH THIRD_MAX_SAL AS (SELECT SAL, DENSE_RANK() OVER(ORDER BY SAL DESC) AS RNK FROM EMPLOYEE)
SELECT DISTINCT SAL AS "3RD_MAX_SAL" FROM THIRD_MAX_SAL WHERE RNK = 3;

--49)Write a Query to display all the employees who are earning more than all the managers.
SELECT ENAME FROM EMPLOYEE WHERE SAL > ALL
(SELECT SAL FROM EMPLOYEE WHERE JOB = 'MANAGER');

--50)Write a Query to display all the employees who are earning more than any of the managers.
SELECT ENAME FROM EMPLOYEE WHERE SAL > ANY
(SELECT SAL FROM EMPLOYEE WHERE JOB = 'MANAGER');

--51)Select empno, job and salary of all the analyst who are earning more than any of the manager.
SELECT EMPNO, JOB, SAL FROM EMPLOYEE WHERE JOB = 'ANALYST' AND SAL > ANY
(SELECT SAL FROM EMPLOYEE WHERE JOB = 'MANAGER');

--52) Select the department name and location of all the employee working for clark
SELECT D.DNAME, D.LOC FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO 
WHERE E.MGR = (SELECT EMPNO FROM EMPLOYEE WHERE ENAME = 'CLARK');

--53) Find employees who earn more than their manager
SELECT E.ENAME FROM EMPLOYEE E JOIN EMPLOYEE M ON E.MGR = M.EMPNO 
WHERE E.SAL > M.SAL;

--54). Display the employee hierarchy (employee → manager → manager's manager)
SELECT E.ENAME AS EMPLOYEE, M.ENAME MANAGER, M1.ENAME "MANAGER'S MANAGER" FROM EMPLOYEE E JOIN EMPLOYEE M ON E.MGR = M.EMPNO 
JOIN EMPLOYEE M1 ON M.MGR = M1.EMPNO;

--55). List all departments and the number of managers in each
SELECT DEPTNO, COUNT(*) FROM EMPLOYEE WHERE JOB = 'MANAGER' GROUP BY DEPTNO;

--56) List the top 3 highest paid employees in each department
WITH CTE AS (SELECT ENAME, DEPTNO, SAL, DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS RNK FROM EMPLOYEE)
SELECT DEPTNO,ENAME FROM CTE WHERE RNK < 4;

--57). Find employees who joined in the same year as their manager
SELECT E.ENAME, EXTRACT(YEAR FROM E.HIREDATE), M.ENAME, EXTRACT(YEAR FROM M.HIREDATE) FROM EMPLOYEE E JOIN EMPLOYEE M
ON E.MGR = M.EMPNO WHERE EXTRACT(YEAR FROM E.HIREDATE) = EXTRACT(YEAR FROM M.HIREDATE);

--58) Find the department with the highest total salary
WITH CTE AS
(
    SELECT
        DEPTNO,
        SUM(SAL) AS TOTAL_SAL,
        DENSE_RANK() OVER
        (
            ORDER BY SUM(SAL) DESC
        ) AS RNK
    FROM EMPLOYEE
    GROUP BY DEPTNO
)
SELECT DEPTNO, TOTAL_SAL FROM CTE WHERE RNK = 1;

--59). Show departments where average salary is higher than company average salary
SELECT D.DEPTNO, D.DNAME, AVG(E.SAL) AS AVERAGE_SALARY FROM EMPLOYEE E JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO GROUP BY D.DEPTNO, D.DNAME
HAVING AVG(E.SAL) > (SELECT AVG(SAL) FROM EMPLOYEE);

--60). For each employee, show the name of the highest-paid person in their department
SELECT
    ENAME AS EMPLOYEE_NAME,
    DEPTNO,
    FIRST_VALUE(ENAME) OVER (
        PARTITION BY DEPTNO
        ORDER BY SAL DESC
    ) AS HIGHEST_PAID_EMPLOYEE
FROM EMPLOYEE;